In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import f1_score
from sklearn.metrics.pairwise import cosine_similarity
from statistics import harmonic_mean
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import HashingVectorizer

In [2]:
df = pd.read_csv('Coursera.csv')
df.head()

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills
0,Write A Feature Length Screenplay For Film Or ...,Michigan State University,Beginner,4.8,https://www.coursera.org/learn/write-a-feature...,Write a Full Length Feature Film Script In th...,Drama Comedy peering screenwriting film D...
1,Business Strategy: Business Model Canvas Analy...,Coursera Project Network,Beginner,4.8,https://www.coursera.org/learn/canvas-analysis...,"By the end of this guided project, you will be...",Finance business plan persona (user experien...
2,Silicon Thin Film Solar Cells,�cole Polytechnique,Advanced,4.1,https://www.coursera.org/learn/silicon-thin-fi...,This course consists of a general presentation...,chemistry physics Solar Energy film lambda...
3,Finance for Managers,IESE Business School,Intermediate,4.8,https://www.coursera.org/learn/operational-fin...,"When it comes to numbers, there is always more...",accounts receivable dupont analysis analysis...
4,Retrieve Data using Single-Table SQL Queries,Coursera Project Network,Beginner,4.6,https://www.coursera.org/learn/single-table-sq...,In this course you�ll learn how to effectively...,Data Analysis select (sql) database manageme...

In [3]:
df.drop_duplicates(inplace=True)

#drop Coursera Project Network rows in University
df = df[df['University'] != 'Coursera Project Network']

#drop rows with Not Calibrated in Course Rating
df = df[df['Course Rating'] != 'Not Calibrated']

In [4]:
#df.drop('Unnamed: 0',axis=1,inplace=True)
print(df.isna().sum())
df.head()

Course Name           0
University            0
Difficulty Level      0
Course Rating         0
Course URL            0
Course Description    0
Skills                0
dtype: int64

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills
0,Write A Feature Length Screenplay For Film Or ...,Michigan State University,Beginner,4.8,https://www.coursera.org/learn/write-a-feature...,Write a Full Length Feature Film Script In th...,Drama Comedy peering screenwriting film D...
2,Silicon Thin Film Solar Cells,�cole Polytechnique,Advanced,4.1,https://www.coursera.org/learn/silicon-thin-fi...,This course consists of a general presentation...,chemistry physics Solar Energy film lambda...
3,Finance for Managers,IESE Business School,Intermediate,4.8,https://www.coursera.org/learn/operational-fin...,"When it comes to numbers, there is always more...",accounts receivable dupont analysis analysis...
6,Doing Business in China Capstone,The Chinese University of Hong Kong,Advanced,3.3,https://www.coursera.org/learn/doing-business-...,Doing Business in China Capstone enables you t...,marketing plan Planning Marketing consumpti...
7,"Programming Languages, Part A",University of Washington,Intermediate,4.9,https://www.coursera.org/learn/programming-lan...,This course is an introduction to the basic co...,inference ml (programming language) higher-o...

In [27]:
df.to_csv('CourseraData.csv')

In [20]:
vectorizer = TfidfVectorizer(stop_words='english')
vectors = vectorizer.fit_transform(df['Course Name'])

In [22]:
def recommend_by_course_title (title, recomm_count=10) : 
    title_vector = vectorizer.transform([title])
    cosine_sim = cosine_similarity(vectors, title_vector)
    idx = np.argsort(np.array(cosine_sim[:,0]))[-recomm_count:]
    sdf = df.iloc[idx].sort_values(by='Course Rating', ascending=False)
    return sdf

In [29]:
df.columns

Index(['Course Name', 'University', 'Difficulty Level', 'Course Rating',
       'Course URL', 'Course Description', 'Skills'],
      dtype='object')

In [28]:
recommend_by_course_title('Machine Learning')

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills
2923,Machine Learning: Regression,University of Washington,Beginner,4.8,https://www.coursera.org/learn/ml-regression,Case Study - Predicting Housing Prices In our...,Regression General Statistics lasso (statist...
3230,Machine Learning for All,University of London,Conversant,4.7,https://www.coursera.org/learn/uol-machine-lea...,"Machine Learning, often called Artificial Inte...",robotics Machine Learning Artificial Neural ...
2405,Machine Learning With Big Data,University of California San Diego,Beginner,4.6,https://www.coursera.org/learn/big-data-machin...,Want to make sense of the volumes of data you ...,statistical classification knime data cluste...
1349,Machine Learning with Python,IBM,Beginner,4.6,https://www.coursera.org/learn/machine-learnin...,This course dives into the basics of machine l...,Logistic Regression Algorithms Human Learnin...
384,Introduction to Machine Learning,Duke University,Beginner,4.6,https://www.coursera.org/learn/machine-learnin...,This course will provide you a foundational un...,Machine Learning Regression Convolutional Ne...
86,Project Planning and Machine Learning,University of Colorado Boulder,Beginner,4.4,https://www.coursera.org/learn/industrial-iot-...,This course can also be taken for academic cre...,Machine Learning Algorithms Planning interne...
496,Practical Machine Learning,Johns Hopkins University,Beginner,4.4,https://www.coursera.org/learn/practical-machi...,One of the most common tasks performed by data...,Machine Learning Algorithms Human Learning R...
2250,Data for Machine Learning,Alberta Machine Intelligence Institute,Beginner,4.4,https://www.coursera.org/learn/data-machine-le...,This course is all about data and how it is cr...,General Statistics evaluation Deep Learning ...
2707,Machine Learning for Data Analysis,Wesleyan University,Intermediate,4.2,https://www.coursera.org/learn/machine-learnin...,Are you interested in predicting future outcom...,Algorithms Data Analysis numbers (spreadshee...
3215,Fundamentals of Machine Learning in Finance,New York University,Advanced,3.3,https://www.coursera.org/learn/fundamentals-ma...,The course aims at helping students to be able...,mathematical finance optimal control Machine...

In [24]:
def recommend_default_top_10():
    return df.sort_values(by='Course Rating', ascending=False).head(10)

In [26]:
recommend_default_top_10().to_csv('Default10.csv')